---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: freehck.add_repo
      add_repo_name: docker-stable
      add_repo_string: 'deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
      add_repo_key: 'https://download.docker.com/linux/ubuntu/gpg'
      when:
        - ansible_distribution == 'Ubuntu'
    - role: freehck.add_repo
      add_repo_name: docker-stable
      add_repo_string: 'deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
      add_repo_key: 'https://download.docker.com/linux/debian/gpg'
      when:
        - ansible_distribution == 'Debian'
    - role: freehck.add_repo
      add_repo_name: docker-stable
      add_repo_url: 'https://download.docker.com/linux/centos/$releasever/$basearch/stable'
      add_repo_key: 'https://download.docker.com/linux/centos/gpg'
      when:
        - ansible_distribution == 'Centos'
